CREATE SEQUENCE hotelandes_sequence;




CREATE TABLE A_HOTEL
    ( idHotel NUMBER,
    nombre VARCHAR2(225 BYTE),
    ubicacion VARCHAR2(225 BYTE) NOT NULL,
    paginaweb VARCHAR2(225 BYTE) NOT NULL, 
    NUMERO NUMBER,
    CONSTRAINT HOTEL_PK PRIMARY KEY (idHotel));



CREATE TABLE A_EMPLEADO
    (idEmpleado NUMBER,
    nombre VARCHAR2(225 BYTE) NOT NULL,
    CELULAR NUMBER,
    CORREO VARCHAR2(225 BYTE) NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (idEmpleado));



CREATE TABLE A_METODO_PAGO
    (idMetodoPago NUMBER,
    tipo VARCHAR2(225 BYTE),
    nombre VARCHAR2(225 BYTE),
    CONSTRAINT B_METODO_PAGO_PK PRIMARY KEY (idMetodoPago));    





CREATE TABLE A_CUENTA
    (idCuenta NUMBER,
    total NUMBER,
    CONSTRAINT CUENTA_PK PRIMARY KEY (idCuenta) );




CREATE TABLE A_PLAN_CONSUMO
    (idPlanConsumo NUMBER,
    nombre NUMBER,
    costo VARCHAR2(225 BYTE) NOT NULL,
    vigencia DATE,
    CONSTRAINT PLAN_CONSUMO_PK PRIMARY KEY(idPlanConsumo));




CREATE TABLE A_SERVICIO_SOLICITADO
    (idServicio NUMBER,
    numpersonas NUMBER,
    Costo NUMBER,
    CONSTRAINT SERVICIO_SOLICITADO_PK PRIMARY KEY (idServicio));





CREATE TABLE A_SERVICIO
    (idServicio NUMBER,
    nombre VARCHAR2(225 BYTE),
    DESCRIPCION VARCHAR2(225 BYTE),
    area VARCHAR2(225 BYTE),
    CONSTRAINT SERVICIO_PK PRIMARY KEY (idServicio));



CREATE TABLE A_TIPO_HABITACION
    (tipoHabitacion VARCHAR2(225 BYTE),
    CAPACIDAD NUMBER,
    AREA NUMBER,
    CONSTRAINT TIPO_HABITACIONN_PK  PRIMARY KEY(tipoHabitacion));














CREATE TABLE A_HABITACION
    (idHabitacion NUMBER,
    nombre VARCHAR2(225 BYTE),
    CAPACIDAD NUMBER,
    tipoHabitacion NUMBER,
    numeroHabitacion NUMBER,
    idEmpleado NUMBER,
    CONSTRAINT ID_HABITACION_PK  PRIMARY KEY (idHabitacion));

ALTER TABLE A_HABITACION
ADD CONSTRAINT fk_b_idempleadoo
    FOREIGN KEY (idEmpleado)
    REFERENCES A_EMPLEADO(idEmpleado)
ENABLE;





CREATE TABLE A_HABITACION_OFERTADA
    (idHotel NUMBER,
    idHabitacion NUMBER,
    CONSTRAINT HABITACION_OFERTADA_PK PRIMARY KEY(idHotel,idHabitacion));

ALTER TABLE A_HABITACION_OFERTADA
ADD CONSTRAINT fk_b_idhabitacion
    FOREIGN KEY (idHabitacion)
    REFERENCES A_HABITACION(idHabitacion)
ENABLE;



CREATE TABLE A_CLIENTE
   (idCliente NUMBER,
   numero NUMBER,
   NOMBRE VARCHAR2(225 BYTE) NOT NULL,
   APELLIDO VARCHAR2(225 BYTE) NOT NULL,
   CORREO VARCHAR2(225 BYTE) NOT NULL,
   idMetodoPago NUMBER,
   idHotel NUMBER,
   CONSTRAINT CLIENTE_PK PRIMARY KEY (idCliente));

ALTER TABLE A_CLIENTE
ADD CONSTRAINT fk_b_metodopago
    FOREIGN KEY (idMetodoPago)
    REFERENCES A_METODO_PAGO(idMetodoPago)
ENABLE;


ALTER TABLE A_CLIENTE
ADD CONSTRAINT fk_b_idhotel
    FOREIGN KEY (idHotel)
    REFERENCES A_HOTEL(idHotel)
ENABLE;

CREATE TABLE A_RESERVA
    (idReserva NUMBER,
    fechaEntrada DATE,
    fechaSalida DATE,
    numeroPersonas NUMBER,
    idCliente NUMBER,
    CONSTRAINT RESERVA_PK  PRIMARY KEY(idReserva));

ALTER TABLE A_RESERVA
ADD CONSTRAINT fk_b_idcliente
    FOREIGN KEY (idCliente)
    REFERENCES A_Cliente(idCliente)
ENABLE;



CREATE TABLE A_TIPO_RESERVA
    (idReserva NUMBER,
    idPlanConsumo NUMBER, 
    CONSTRAINT TIPO_RESERVA_PK PRIMARY KEY  (idReserva));

ALTER TABLE A_TIPO_RESERVA
ADD CONSTRAINT fk_b_idplandeconsumo
    FOREIGN KEY (idPlanConsumo)
    REFERENCES A_PLAN_CONSUMO(idPlanConsumo)
ENABLE;


ALTER TABLE A_TIPO_RESERVA
ADD CONSTRAINT fk_b_reserva
    FOREIGN KEY (idReserva)
    REFERENCES A_RESERVA(idReserva)
ENABLE;








CREATE TABLE A_HABITACION_RESERVADA
    (idHabitacion NUMBER,
    idReserva NUMBER,
    idCuenta NUMBER,
    CONSTRAINT HABITACION_RESERVADA_PK  PRIMARY KEY(idHabitacion));

ALTER TABLE A_HABITACION_RESERVADA
ADD CONSTRAINT fk_b_idreserva
    FOREIGN KEY (idReserva)
    REFERENCES A_Reserva(idReserva)
ENABLE;


ALTER TABLE A_HABITACION_RESERVADA
ADD CONSTRAINT fk_b_idcuenta
    FOREIGN KEY (idCuenta)
    REFERENCES A_CUENTA(idCuenta)
ENABLE;





CREATE TABLE A_SERVICIO_OFRECIDO
    (idServicio NUMBER,
    idHotel NUMBER,
    CONSTRAINT PK_SERVICIO_OFRECIDO_PK PRIMARY KEY (idServicio,idHotel));

ALTER TABLE A_SERVICIO_OFRECIDO
ADD CONSTRAINT fk_b_idhootel
    FOREIGN KEY (idHotel)
    REFERENCES A_HOTEL(idHotel)
ENABLE;  




CREATE TABLE A_CLIENTE_ACTIVO
    (idCliente NUMBER,
    idReserva NUMBER,
    CONSTRAINT CLIENTE_ACTIVO_PK PRIMARY KEY(idCliente)); 

ALTER TABLE A_CLIENTE_ACTIVO
ADD CONSTRAINT fk_b_idReservaa
    FOREIGN KEY (idReserva)
    REFERENCES A_RESERVA(idReserva)
ENABLE;    








CREATE TABLE A_EMPLEADO_ACTIVO
    (idHotel NUMBER,
    idEmpleado NUMBER,
    CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY(idHotel));

ALTER TABLE A_EMPLEADO_ACTIVO
ADD CONSTRAINT fk_b_idEmpleadooo
    FOREIGN KEY (idEmpleado)
    REFERENCES A_EMPLEADO(idEmpleado)
ENABLE; 





CREATE TABLE A_CUENTA_CARGADA
    (idCuenta NUMBER,
    idServicio NUMBER,
    CONSTRAINT CUENTA_CARGADA_PK PRIMARY KEY (idCuenta,idServicio));

ALTER TABLE A_CUENTA_CARGADA
ADD CONSTRAINT fk_b_idServicioO
    FOREIGN KEY (idServicio)
    REFERENCES A_SERVICIO(idServicio)
ENABLE; 









CREATE TABLE A_PLAN_OFRECIDO
    (idPlanConsumo NUMBER,
    idHotel NUMBER,
    CONSTRAINT PLAN_OFRECIDO_PK PRIMARY KEY(idPlanConsumo));

ALTER TABLE A_PLAN_OFRECIDO
ADD CONSTRAINT fk_b_idHotelL
    FOREIGN KEY (idHotel)
    REFERENCES A_HOTEL(idHotel)
ENABLE; 


COMMIT;
